/*****************************************************************************
 * XxcssMatCmRpSubmit.java
 *
 * Copyright 2001-2003 Cisco Systems, Inc. All Rights Reserved.
 * This software is the proprietary information of  Cisco Systems, Inc.
 *
 * NOTE:
 * This file was generated by the genJava script.  Please only make
 * changes to the file within protect blocks to ensure your changes are 
 * preserved when this file is next regenerated.
 * 
 *****************************************************************************/

package com.cisco.mcm.genJava;

/* Begin generated import statements */
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;

import oracle.jdbc.driver.OracleTypes;
import oracle.sql.ARRAY;
import oracle.sql.ArrayDescriptor;
import oracle.sql.STRUCT;

import com.cisco.ca.fea.daoservices.DAOServices;
import com.cisco.ca.fea.daoservices.util.ConnectionUtil;
import com.cisco.ea.dbpool.EACallableStatementFacade;
import com.cisco.mcm.bo.McmReportContext;
import com.cisco.mcm.dao.oracletypes.OraErrorObj;
import com.cisco.mcm.dao.oracletypes.OraMatReportParamsTbl;
 


/* End generated import statements */

/* BEGIN PROTECT_BLOCK user_imports */
/* END PROTECT_BLOCK user_imports */

 


public class XxcssMatCmRpSubmit extends Object implements java.io.Serializable {

    private static XxcssMatCmRpSubmit theInstance=null;
    
/* BEGIN PROTECT_BLOCK user_member_variables */
/* END PROTECT_BLOCK user_member_variables */

    


/* BEGIN PROTECT_BLOCK user_public_constants */
/* END PROTECT_BLOCK user_public_constants */


/* BEGIN PROTECT_BLOCK user_static_initializers */
/* END PROTECT_BLOCK user_static_initializers */


    public static synchronized XxcssMatCmRpSubmit getInstance() {
        if (theInstance==null) {
            theInstance = new XxcssMatCmRpSubmit();
        }
        return theInstance;
    }
    
    private XxcssMatCmRpSubmit() {
/* BEGIN PROTECT_BLOCK user_private_constructor */
/* END PROTECT_BLOCK user_private_constructor */

    }
    

    
    private static ARRAY buildOracleArrayFromList(Connection conn,List list,com.cisco.mcm.genJava.XxcssSsfUpldParmObjType dummy)
        throws SQLException {
        //ARRAY oracleArray=null;
        com.cisco.mcm.genJava.XxcssSsfUpldParmObjType element=null;
        Object[] jarray=null;
        STRUCT struct=null;
        ArrayDescriptor desc=
            ArrayDescriptor.createDescriptor("APPS.XXCSS_SSF_UPLD_PARM_TAB_TYPE",conn);
        int i=0;
        if (list!=null) {
            jarray=new Object[list.size()];
            Iterator iterator=list.iterator();
            while (iterator.hasNext()) {
                element=(com.cisco.mcm.genJava.XxcssSsfUpldParmObjType)iterator.next();
                struct=element.asStruct(conn);
                jarray[i++]=struct;
            }
        }
        return new ARRAY(desc,conn,jarray);
    }

       

    public void submitprogramrequest(
        DAOServices services,
        String ccoUserid,
        String programName,
        String email,
        String emailCc,
        String emailBcc,
        OraMatReportParamsTbl parmTab,
        BigDecimal requestId,
        BigDecimal[] requestId1,
        String[] errorObj,
        String traceLevel,McmReportContext matReportContext)
        throws SQLException,InstantiationException,IllegalAccessException {
        Connection conn=null;
        CallableStatement stmt=null;
       // EACallableStatementFacade stmt = null;
        //OraErrorObj errorObj2 = null;
        //String error = null;
        try {
           
            conn = services.borrowConnection();
            stmt =  conn.prepareCall("begin APPS.xxcss_mat_cm_rp_submit.submitprogramrequest(:1,:2,:3,:4,:5,:6,:7,:8,:9,:10); end;");
            stmt.setString(1,ccoUserid);
            stmt.setString(2,programName);
            stmt.setString(3,email);
            stmt.setString(4,emailCc);
            stmt.setString(5,emailBcc);
            stmt.setObject(6,parmTab);
            stmt.setBigDecimal(7,requestId);
            stmt.registerOutParameter(8, OracleTypes.NUMBER);
            /*stmt.registerOutParameter(9, OracleTypes.STRUCT,
		    "xxcss_sms3_o.XX_CM_ERROR_OBJ_TYPE");*/
            stmt.registerOutParameter(9, OracleTypes.NUMBER);
            stmt.setString(10,traceLevel);
            stmt.execute();
           
            requestId1[0]=(BigDecimal)stmt.getBigDecimal(8);
        
           if(requestId1[0]!=null)
        	matReportContext.setRequestID(requestId1[0].intValue());
            
        } finally  {
            try {
                ConnectionUtil.closeQuietly(stmt);
            } finally {
                services.returnConnection(conn);
            }
        }
    }


    
/* BEGIN PROTECT_BLOCK user_java_code */
/* END PROTECT_BLOCK user_java_code */

}
