/*****************************************************************************
 * XxcssMatConInfoType.java
 *
 * Copyright 2001-2003 Cisco Systems, Inc. All Rights Reserved.
 * This software is the proprietary information of  Cisco Systems, Inc.
 *
 * NOTE:
 * This file was generated by the genJava script.  Please only make
 * changes to the file within protect blocks to ensure your changes are 
 * preserved when this file is next regenerated.
 * 
 *****************************************************************************/

package com.cisco.mcm.genJava;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.GregorianCalendar;

import oracle.sql.CHAR;
import oracle.sql.CharacterSet;
import oracle.sql.STRUCT;
import oracle.sql.StructDescriptor;


/* BEGIN PROTECT_BLOCK user_imports */
/* END PROTECT_BLOCK user_imports */

 
public class XxcssMatConInfoType 
/* BEGIN PROTECT_BLOCK user_extends */
/* END PROTECT_BLOCK user_extends */

implements java.io.Serializable,Cloneable 
/* BEGIN PROTECT_BLOCK user_implements */
/* END PROTECT_BLOCK user_implements */

{



    public static java.sql.Timestamp MISSING_DATE;
    public static final BigDecimal MISSING_NUM=new BigDecimal("9.99E125");
    public static final String MISSING_CHAR=new String(new byte[]{0});
    public static Class factoryClass = XxcssMatConInfoType.class;

    static {     
        GregorianCalendar gc = new GregorianCalendar(4713,0,1);
        gc.set(GregorianCalendar.ERA,GregorianCalendar.BC);
        java.util.Date d=gc.getTime();
        MISSING_DATE=new java.sql.Timestamp(d.getTime());
    };

    public static void setFactoryClass(Class aFactoryClass) {
        factoryClass = aFactoryClass;
    }
    
    public static XxcssMatConInfoType newInstance()
        throws InstantiationException, IllegalAccessException {
        return (XxcssMatConInfoType) factoryClass.newInstance();
    }

public XxcssMatConInfoType() {
        instanceId=MISSING_NUM;
        serialNumber=MISSING_CHAR;
        contractNumber=MISSING_CHAR;
        contractId=MISSING_NUM;
        contractStatus=MISSING_CHAR;
        contractStartDate=MISSING_DATE;
        contractEndDate=MISSING_DATE;
        priceType=MISSING_CHAR;
        svcId=MISSING_NUM;
        svcStatus=MISSING_CHAR;
        svcStartDate=MISSING_DATE;
        svcEndDate=MISSING_DATE;
        svcLevel=MISSING_CHAR;
        svcLevelDesc=MISSING_CHAR;
        contractBilltoLoc=MISSING_CHAR;
        prodSvcId=MISSING_NUM;
        prodStatus=MISSING_CHAR;
        prodStartDate=MISSING_DATE;
        prodEndDate=MISSING_DATE;

/* BEGIN PROTECT_BLOCK user_default_constructor_code */
/* END PROTECT_BLOCK user_default_constructor_code */

}

/* BEGIN PROTECT_BLOCK user_member_variables */
/* END PROTECT_BLOCK user_member_variables */


    private BigDecimal instanceId;
    private String serialNumber;
    private String contractNumber;
    private BigDecimal contractId;
    private String contractStatus;
    private Timestamp contractStartDate;
    private Timestamp contractEndDate;
    private String priceType;
    private BigDecimal svcId;
    private String svcStatus;
    private Timestamp svcStartDate;
    private Timestamp svcEndDate;
    private String svcLevel;
    private String svcLevelDesc;
    private String contractBilltoLoc;
    private BigDecimal prodSvcId;
    private String prodStatus;
    private Timestamp prodStartDate;
    private Timestamp prodEndDate;


    // getter methods
    public BigDecimal getInstanceId() {
        return instanceId;
    }
    public String getSerialNumber() {
        return serialNumber;
    }
    public String getContractNumber() {
        return contractNumber;
    }
    public BigDecimal getContractId() {
        return contractId;
    }
    public String getContractStatus() {
        return contractStatus;
    }
    public Timestamp getContractStartDate() {
        return contractStartDate;
    }
    public Timestamp getContractEndDate() {
        return contractEndDate;
    }
    public String getPriceType() {
        return priceType;
    }
    public BigDecimal getSvcId() {
        return svcId;
    }
    public String getSvcStatus() {
        return svcStatus;
    }
    public Timestamp getSvcStartDate() {
        return svcStartDate;
    }
    public Timestamp getSvcEndDate() {
        return svcEndDate;
    }
    public String getSvcLevel() {
        return svcLevel;
    }
    public String getSvcLevelDesc() {
        return svcLevelDesc;
    }
    public String getContractBilltoLoc() {
        return contractBilltoLoc;
    }
    public BigDecimal getProdSvcId() {
        return prodSvcId;
    }
    public String getProdStatus() {
        return prodStatus;
    }
    public Timestamp getProdStartDate() {
        return prodStartDate;
    }
    public Timestamp getProdEndDate() {
        return prodEndDate;
    }

    // setter methods                       
    public void setInstanceId(BigDecimal aInstanceId) {
        instanceId = aInstanceId;
    }
    public void setSerialNumber(String aSerialNumber) {
        serialNumber = aSerialNumber;
    }
    public void setContractNumber(String aContractNumber) {
        contractNumber = aContractNumber;
    }
    public void setContractId(BigDecimal aContractId) {
        contractId = aContractId;
    }
    public void setContractStatus(String aContractStatus) {
        contractStatus = aContractStatus;
    }
    public void setContractStartDate(Timestamp aContractStartDate) {
        contractStartDate = aContractStartDate;
    }
    public void setContractEndDate(Timestamp aContractEndDate) {
        contractEndDate = aContractEndDate;
    }
    public void setPriceType(String aPriceType) {
        priceType = aPriceType;
    }
    public void setSvcId(BigDecimal aSvcId) {
        svcId = aSvcId;
    }
    public void setSvcStatus(String aSvcStatus) {
        svcStatus = aSvcStatus;
    }
    public void setSvcStartDate(Timestamp aSvcStartDate) {
        svcStartDate = aSvcStartDate;
    }
    public void setSvcEndDate(Timestamp aSvcEndDate) {
        svcEndDate = aSvcEndDate;
    }
    public void setSvcLevel(String aSvcLevel) {
        svcLevel = aSvcLevel;
    }
    public void setSvcLevelDesc(String aSvcLevelDesc) {
        svcLevelDesc = aSvcLevelDesc;
    }
    public void setContractBilltoLoc(String aContractBilltoLoc) {
        contractBilltoLoc = aContractBilltoLoc;
    }
    public void setProdSvcId(BigDecimal aProdSvcId) {
        prodSvcId = aProdSvcId;
    }
    public void setProdStatus(String aProdStatus) {
        prodStatus = aProdStatus;
    }
    public void setProdStartDate(Timestamp aProdStartDate) {
        prodStartDate = aProdStartDate;
    }
    public void setProdEndDate(Timestamp aProdEndDate) {
        prodEndDate = aProdEndDate;
    }


    // other methods


    public XxcssMatConInfoType loadFromStruct(Connection conn,STRUCT struct) 
        throws SQLException,InstantiationException,IllegalAccessException {
        Object[] attributes=struct.getAttributes();
        instanceId=(BigDecimal)attributes[0];
        serialNumber=(String)attributes[1];
        contractNumber=(String)attributes[2];
        contractId=(BigDecimal)attributes[3];
        contractStatus=(String)attributes[4];
        contractStartDate=(Timestamp)attributes[5];
        contractEndDate=(Timestamp)attributes[6];
        priceType=(String)attributes[7];
        svcId=(BigDecimal)attributes[8];
        svcStatus=(String)attributes[9];
        svcStartDate=(Timestamp)attributes[10];
        svcEndDate=(Timestamp)attributes[11];
        svcLevel=(String)attributes[12];
        svcLevelDesc=(String)attributes[13];
        contractBilltoLoc=(String)attributes[14];
        prodSvcId=(BigDecimal)attributes[15];
        prodStatus=(String)attributes[16];
        prodStartDate=(Timestamp)attributes[17];
        prodEndDate=(Timestamp)attributes[18];

/* BEGIN PROTECT_BLOCK user_load_from_struct_code */
/* END PROTECT_BLOCK user_load_from_struct_code */

        return this;
    }
    
    public STRUCT asStruct(Connection conn)
        throws SQLException {
        STRUCT struct=null;
        StructDescriptor sd=
            StructDescriptor.createDescriptor("APPS.XXCSS_MAT_CON_INFO_TYPE",conn);
        Object[] attributes = new Object[]{
            instanceId,
            ((serialNumber==null) ? null : new CHAR(serialNumber,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            ((contractNumber==null) ? null : new CHAR(contractNumber,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            contractId,
            ((contractStatus==null) ? null : new CHAR(contractStatus,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            contractStartDate,
            contractEndDate,
            ((priceType==null) ? null : new CHAR(priceType,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            svcId,
            ((svcStatus==null) ? null : new CHAR(svcStatus,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            svcStartDate,
            svcEndDate,
            ((svcLevel==null) ? null : new CHAR(svcLevel,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            ((svcLevelDesc==null) ? null : new CHAR(svcLevelDesc,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            ((contractBilltoLoc==null) ? null : new CHAR(contractBilltoLoc,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            prodSvcId,
            ((prodStatus==null) ? null : new CHAR(prodStatus,CharacterSet.make(CharacterSet.UTF8_CHARSET))),
            prodStartDate,
            prodEndDate
        };
        struct=new STRUCT(sd,conn,attributes);

/* BEGIN PROTECT_BLOCK user_load_from_struct_code */
/* END PROTECT_BLOCK user_load_from_struct_code */

        return struct;
    }
    
    public static XxcssMatConInfoType newFromStruct(Connection conn,STRUCT struct) 
        throws SQLException,InstantiationException,IllegalAccessException {
        XxcssMatConInfoType newInstance=newInstance();
        newInstance.loadFromStruct(conn,struct);
/* BEGIN PROTECT_BLOCK user_new_from_struct_code */
/* END PROTECT_BLOCK user_new_from_struct_code */

        return newInstance;
    }
    
    public String toString() {
        StringBuffer toStringBuffer = new StringBuffer();
        toStringBuffer.append(getClass());
        toStringBuffer.append("@");
        toStringBuffer.append(super.hashCode());
        toStringBuffer.append("[");
        this.appendToStringAttributes(toStringBuffer);
        toStringBuffer.append("]");
        return toStringBuffer.toString();
    }     

    protected void appendToStringAttributes(StringBuffer sb) {
        sb.append("instanceId=").append(instanceId);
        sb.append(",serialNumber=").append(serialNumber);
        sb.append(",contractNumber=").append(contractNumber);
        sb.append(",contractId=").append(contractId);
        sb.append(",contractStatus=").append(contractStatus);
        sb.append(",contractStartDate=").append(contractStartDate);
        sb.append(",contractEndDate=").append(contractEndDate);
        sb.append(",priceType=").append(priceType);
        sb.append(",svcId=").append(svcId);
        sb.append(",svcStatus=").append(svcStatus);
        sb.append(",svcStartDate=").append(svcStartDate);
        sb.append(",svcEndDate=").append(svcEndDate);
        sb.append(",svcLevel=").append(svcLevel);
        sb.append(",svcLevelDesc=").append(svcLevelDesc);
        sb.append(",contractBilltoLoc=").append(contractBilltoLoc);
        sb.append(",prodSvcId=").append(prodSvcId);
        sb.append(",prodStatus=").append(prodStatus);
        sb.append(",prodStartDate=").append(prodStartDate);
        sb.append(",prodEndDate=").append(prodEndDate);

    }
    
    public Object clone() throws CloneNotSupportedException {
        XxcssMatConInfoType theClone = (XxcssMatConInfoType) super.clone();
        


        return theClone;
    }
    
    public boolean equals(Object obj) {
        boolean retVal = false;
        if (obj != null) {
            retVal = (hashCode()==obj.hashCode());   
        }
        return retVal; 
    }
    
    public int hashCode() {
        StringBuffer hashStringBuffer = new StringBuffer();
        
        hashStringBuffer.append("instanceId=").append(instanceId);
        hashStringBuffer.append("serialNumber=").append(serialNumber);
        hashStringBuffer.append("contractNumber=").append(contractNumber);
        hashStringBuffer.append("contractId=").append(contractId);
        hashStringBuffer.append("contractStatus=").append(contractStatus);
        hashStringBuffer.append("contractStartDate=").append(contractStartDate);
        hashStringBuffer.append("contractEndDate=").append(contractEndDate);
        hashStringBuffer.append("priceType=").append(priceType);
        hashStringBuffer.append("svcId=").append(svcId);
        hashStringBuffer.append("svcStatus=").append(svcStatus);
        hashStringBuffer.append("svcStartDate=").append(svcStartDate);
        hashStringBuffer.append("svcEndDate=").append(svcEndDate);
        hashStringBuffer.append("svcLevel=").append(svcLevel);
        hashStringBuffer.append("svcLevelDesc=").append(svcLevelDesc);
        hashStringBuffer.append("contractBilltoLoc=").append(contractBilltoLoc);
        hashStringBuffer.append("prodSvcId=").append(prodSvcId);
        hashStringBuffer.append("prodStatus=").append(prodStatus);
        hashStringBuffer.append("prodStartDate=").append(prodStartDate);
        hashStringBuffer.append("prodEndDate=").append(prodEndDate);

        return hashStringBuffer.toString().hashCode();
    }
      
/* BEGIN PROTECT_BLOCK user_java_code */
/* END PROTECT_BLOCK user_java_code */

}
